channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - catboost==1.2.8
  - cloudpickle==3.1.2
  - ipywidgets==8.1.8
  - lightgbm==4.6.0
  - matplotlib==3.10.8
  - numpy==1.26.4
  - pandas==2.3.3
  - pickleshare==0.7.5
  - psutil==7.1.3
  - pyarrow==22.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
  - xgboost==3.1.3
name: mlflow-env
